version: "2.2"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9201:9200
    networks:
      - elastic
  sync:
    build: .
    container_name: sync
